RedisExchangeApı.Web/RedisExchangeApı.Web/Models/ErrorViewModel.cs
namespace RedisExchangeApı.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApı.Web.Models;
using System.Diagnostics;

namespace RedisExchangeApı.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApı.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApı.Web.Controllers
{
    public class ListTypeController : Controller
    {
        RedisService _redisService;
        IDatabase db;
        private string listKey = "names";
        public ListTypeController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.getDb(0);

        }
        public IActionResult Index()
        {                 
            List<string> list = new List<string>();
            if (db.KeyExists(listKey))
            {
                db.ListRange(listKey).ToList().ForEach(x=>
                {
                    list.Add(x.ToString());
                });

            }



            return View(list);

        }
        [HttpPost]
        public IActionResult Add(string name)
        {
            db.ListRightPush(listKey, name);

            return RedirectToAction("Index");
        }  

        public IActionResult DeleteItem(string name)
        {
            db.ListRemoveAsync(listKey, name).Wait();

            return RedirectToAction("Index");
        }        
        public IActionResult DeleteFirstItem(string name)
        {
            db.ListLeftPop(listKey);

            return RedirectToAction("Index");
        }
    }
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Controllers/SetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApı.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApı.Web.Controllers
{
	public class SetTypeController : Controller
	{
		RedisService _redisService;
		IDatabase db;
		private string listKey = "hashname";
		public SetTypeController(RedisService redisService)
		{
			_redisService = redisService;
			db = _redisService.getDb(0);

		}
		public IActionResult Index()
		{
			HashSet<string> nameList = new HashSet<string>();
			if (db.KeyExists(listKey))
			{
				db.SetMembers(listKey).ToList().ForEach(x => nameList.Add(x.ToString()));
			}
			return View();
		}
		[HttpPost]
		public IActionResult Add(string name)
		{

			db.KeyExpire(listKey, DateTime.Now.AddMinutes(5));
			db.SetAdd(listKey, name);
			return RedirectToAction("Index");
		}	   
		public async Task< IActionResult> DeleteItem(string name)
		{

			await db.SetRemoveAsync(listKey, name);
			return RedirectToAction("Index");
		}
	}
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApı.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApı.Web.Controllers
{
    public class StringTypeController : Controller
    {
        RedisService _redisService;
        IDatabase db;
        public StringTypeController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.getDb(0);
                
        }
      
        public IActionResult Index()
        {

          
            db.StringSet("name", "Burak İpekçi");
            db.StringSet("user", 100);


            return View();
        }
        public IActionResult Show()
        {
            var value = db.StringGet("name");

            db.StringIncrement("user",1);    // user keyindeki datayı birer birer arttırır
            var get = db.StringGetRange("name", 0, 3); //0. indexden başla ve 3. indexli harfe kadar getir.
          
            if (value.HasValue)
            {
                ViewBag.value = value.ToString();

            }
      


            return View();
        }
    }
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RedisExchangeApı.Web/RedisExchangeApı.Web/Views/ListType/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Views/ListType/Index.cshtml
@model List<string>
@{
	ViewData["Title"] = "Index";
}
<a asp-action="DeleteFirstItem">Baştan sil</a>
<form method="post" asp-action="add" enctype="application/x-www-form-urlencoded">
	<input type="text" name="name" />
	<button type="submit">Kaydet</button>


</form>
@foreach(var item in Model)	{
	
	
	
	<h2>@item<a asp-controller="ListType" asp-action="DeleteItem" asp-route-name="@item">sil</a></h2>
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Views/SetType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RedisExchangeApı.Web/RedisExchangeApı.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisExchangeApı.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RedisExchangeApı.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisExchangeApı.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RedisExchangeApı.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RedisExchangeApı.Web/RedisExchangeApı.Web/Views/StringType/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Index";
}
<h1>Index</h1>

RedisExchangeApı.Web/RedisExchangeApı.Web/Views/StringType/Show.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Show";
}
<h1>@ViewBag.value</h1>